---
- hosts: local
  gather_facts: false
  become: true

  tasks:
    - name: create hubcontroller project
      command: oc new-project hub-controller2
      ignore_errors: True

    - name: download cacerts file
      command: wget -q -L  https://raw.githubusercontent.com/nexus-Six/openshift-robot-hackathon/master/hub_controller/jks/cacerts -O ./cacerts   

    - name: create cacert jks configmap
      block:
        - name: new cacert
          command: oc create configmap cacerts --from-file=./cacerts
      rescue:
        - name: update cacert
          shell: oc create configmap cacerts --from-file=./cacerts --dry-run -o yaml | oc replace -f -

    - name: download robotmapping configmap file
      get_url:
        url: https://raw.githubusercontent.com/nexus-Six/openshift-robot-hackathon/master/hub_controller/templates/robotmapping-configmap.yaml
        dest: ./robotmapping-configmap.yaml
    
    - name: create configmap robotmapping jks configmap
      command: oc create -f ./robotmapping-configmap.yaml
      ignore_errors: True            

      
    


