= Robot Hackathon - Java module

Robot Services Ltd has provided a basic Spring Boot-based Java application to 
quickly get you started with your first robot application. It's provided in a 
Git (Gogs) repository hosted on the OpenShift cluster. 

To get this application into your workspace:

* In your Che workspace, click *Import Project*
* In the *Import project* window:
** Choose *GIT*
** *URL*: http://gogs-lab-infra.apps.berlin-<CHANGEME>.openshiftworkshop.com
** *Name*: Adapt the name to something sensible
* In the next dialog choose *Java -> Maven*
* Click *Save*

==== Login *oc* to OpenShift from CodeReady workspace

Before deploying applications from your Che workspace to OpenShift, you have to 
login the OpenShift client (oc) to the OpenShift environment. 

Get the login string from the OpenShift web UI:

* In the web UI, click the top right question mark, choose *Command Line Tools*
* Now a form opens, copy the *oc login...* string *using the copy button*
* Paste into the Che terminal, press *Enter*
* You should get a welcome message as you are now logged into OpenShift
* Try running `oc whoami` to make sure

=== Running the Application Locally

*Open a new terminal* in your Che workspace by clicking the *+* sign in the 
lower workspace pane. Change into your project directory:

----
cd /projects/robot-hackathon-<GUID>
----

Now build and run the application locally:

----
mvn spring-boot:run
----

WARNING: You should do this in a new terminal window because you can't stop the 
application with Ctrl-C.

Now your application should run in the embedded Tomcat server. To access the 
application web frontend, look up the URL:

* Again using the *+* sign, open a *Servers* view.
* Under *Reference* search for *Tomcat8*
* Click the URL, this will take you to the web page

By clicking the *Run* button you start the *run* method of the application. 
Using the initial check out this will print a log message you will see in the 
terminal Tomcat is running in.

=== Changing the Application

Now it's time to make the first change to the application code. The code 
structure is standard-Maven, have a look around. The log message you just 
saw is triggered in the *run()* method of class 
`../src/main/java/io/openshift/booster/service/RobotEndpoint.java`

As a first example go and change the log message and the standard output:

----
public Object run() {
        System.out.println("Hello Team");
        String response = "Hello Team";
        // Example GET invokation of the Robot API
----

Springboot will take care of recompiling and hot-swapping your code change. 
Wait until this has finished and run again by pressing *Run* on the web page.

Do this as long as you want, the goal is to get familiar with the process.

TIP: When you are finished changing code, close the terminal Tomcat is running 
in.

=== Deploying the Application to OpenShift

Until now the application runs locally in your Che workspace. To run it as a 
containerized service in OpenShift, deployable where ever you want, you have to 
build and deploy a container image from your application. And guess what? It's 
easy!

To deploy to OpenShift, run:

----
mvn clean fabric8:deploy -Popenshift -DskipTests
----

This time, the command will return because the code was deployed in a 
container/pod in OpenShift. Go to the OpenShift web console and open your 
project. You might see the build still running, after it has finished, the 
route to externally access the application will be visible in the upper right 
corner. It will look like:

----
http://hub-controller-live-<GUID>-project.apps-<CHANGEME>.generic.opentlc.
com 
----

Clicking the route will take you to your applications web page again! But this 
time in the cloud!

Try running the *run()* method again, it should do the same as before. To see 
the log message, click the blue circle with the pod name and click on the 
*Logs* tab.
