= Robot Hackathon - Python module

== Welcome Python Developers!

Good choice of programming language Team <GUID>! With the help of Python you will control your robot in no time!

Robot Services Ltd has provided a basic Python application to 
quickly get you started with your first robot application.

== Clone the Python Example into your Gogs Git Repo

. Login into http://gogs-lab-infra.apps.berlin-618f.openshiftworkshop.com[Gogs^] with `*<GUID>*` and the provided password.
. Click on the `*+*` in the upper right and choose `*New Migration*`.
. Fill in the `*Clone Address*` field: `*https://github.com/goetzrieger/robot-hackathon-starter-app-python.git*`
. In the `*Repository Name*` field write `*<GUID>-python*`
. Click on `*Migrate Repository*`

== Configure and Run

In this Hackathon you'll use Eclipse Che for development (you can of course use any dev tool you want as long as you can connect to your Git repo in Gogs, but Che is fun). To get started you have to:

* Create a new Che Workspace for your programming language of choice, you should have done this already. 
* Clone your Gogs repository into a Che project
* Do some basic configuration 
* Start the application for the first time

=== Clone Gogs Repo into Che Workspace

If you don't have http://che-lab-infra.apps.berlin-618f.openshiftworkshop.com/[Eclipse Che^] open in your browser, login as your team. Then open the `Workspace` you already created: choose it in the *Dashboard* or *Workspaces* view and click the *OPEN* button in the upper right corner. 

To start a new project with your sources from Gogs:

* Click `*Import Project*`, choose `GIT` as Version Control System.
* Paste your GIT Project URL from Gogs. Get it by copying the HTTP URL from your Gogs account, it should look like `*http://gogs-lab-infra.apps.berlin-618f.openshiftworkshop.com/<TEAMNAME>/<TEAMNAME>-python.git`*
* Edit the link and add your username and passwort to it for push authentication. It should now look like this: `*http://<GUID>:<PASSWORD>@gogs-lab-infra.apps.berlin-618f.openshiftworkshop.com/<TEAMNAME>/<TEAMNAME>-php*`
* Click on `*Import*`
* In the project configuration window that comes up next choose `*Python*`
* Click `*Save*`.

In addition you have to edit the GIT user profile in Che: 

* In the menu choose `*Profile->Prereferences*`
* Select `*GIT Committer*`
* Enter `*<TEAMNAME>*` in the name field and `*<TEAMNAME>@example.com*` in the E-Mail field. 
* Click on `*Save*` and close the Window.

Now is a good time to have a first look at the Python template application. It's deliberately simple as it's just meant to be a starting point. It's based on the Flask framework, it creates a simple webpage with a button to allow you to execute a method *run*. 

=== Basic Application Configuration

Because the application you cloned is a template to make it work with your robot you have to configure the connection details first:

* Expand the project tree and open the *config.py* file by double-clicking it
* Change the *URI* and *APITOKEN* parameters
** You could look up the URI in your 3Scale account, it should be *https://api-2445582274375.staging.gw.apicast.io/api/robot/*.
** For *APITOKEN* fill in your team name to route your requests to the proper robot

== First build in OpenShift.

You're ready to run the application the first time! But first make sure your team robot is connected to the power supply and switched on!

Open the https://master.berlin-618f.openshiftworkshop.com/console[OpenShift Web UI^]. If not already logged in, log in with `*<GUID>*` and the provided password.

. Click on the `*<GUID>-project*`
. Click on `*Browse Project->Languages->Python*` and choose `*Phython*`.
. Click on `*Next*`
. As `Application Name` use `*<GUID>-phython*` and as `GIT Repository` use `*http://gogs-lab-infra.apps.berlin-618f.openshiftworkshop.com/<GUID>/<GUID>-php*`
. Click on `*Create*` and `*Close*`
. Click on `*Overview*` and then on the little `*>*` beside the `Deployment Config`.

=== Check it

After the build is complete, click the Link to your newly created application. It'll take you to the Python Robot Control Landing Page. From here you can execute a simple connectivity test of your robot by clicking *Status*.

=== Run it

To execute the *run* method click the `*Run*` button. Execution will take some seconds but then the robot should move some centimeters forward.

If the robot moved, your setup is good and ready to go for the Hackathon!

== Start Hacking

The easiest way to add code to control the robot is to open the file *wsgi.py* and then edit the *run* method. To get started just comment out 

and remove the comments from

to commit the code changes to Git:

* In Che click on `*Git->Commit*`
* Type in a Commit message
* Check the `*Push commited changes*` checkbox
* Click on `*Commit*`.

After the code changes have been pushed to Git/Gogs you can build a new version of your app in OpenShift.

== Training Missions

Here are some training missions to get you started.

*Task:* Make your robot drive in a square with approx 20cm edge length

*Hints:*

* Plan what your robot should do, check the space for the square.
* Look up the robot API calls you might need in 3Scale
* Add code in the *run* method and commit/push it with Eclipse Che
* Keep in mind that motors ans sensors of the robot are not 100 % precise, so you may need to compensate in your code
* Deploy to OpenShift
* Test your code by running it from the control page

WARNING: Solution Below!
----
mmm
----
