= Robot Hackathon - Team <GUID>

== Introduction

Welcome Team <GUID>!

You are a special mission super coder/geek. Your mission is to complete 
several assignements using a state-of-the-art robot in a dangerous environment. 
The robot is provided by Robot Services, Ltd. Because speed is of utmost 
importance you will utilize agile and DevOps based development 
methodologies. To get productive quickly you will use the container 
platform OpenShift which will be provided by Robot Services. 

== Your Adventure starts... connect to the Robot

=== Access the API

Robot Service Ltd provides access to their robots through an API gateway based 
on the 3Scale API Management platform.

TIP: As the robots are accessed over a public API, it's important to 
restrict and limit who can use the API. The API management platform takes care 
of role-based access control, setting up accounts, monitoring, routing, traffic 
shaping and more.

Okay, let's get started. Head over to `https://rh-test.3scale.net/[https://rh-test.3scale.net/^]` and:

* Click on `*SIGN IN*` in the upper right
* Login with your team credentials (`*<GUID>*`, password as provided)
* After login you will see the API key you need to access the robot API

TIP: Look around in the 3Scale web UI, you will see examples of how to invoke 
the API of your robot. 3Scale will take care of routing your requests to the 
proper robot. 

WARNING: The most important information is the *Key* from the *Credentials* 
box. Using this key as *user_key* in your API calls takes care of routing the 
requests to the proper robot. Your *Key* is: `*<GUID>*`

==== Testing the API

The easiest way to test the connection to the Hub-Controller is to use the 
curl commandline under *Run your requests* from a terminal. This will test the 
connection to the Hub-Controller, *not* the robot!

----
curl https://api-2445582274375.staging.gw.apicast.io:443/api/robot/status?user_key=<GUID>
OK
----

If you don't have a notebook with `curl` don't worry, you can test this also through the 3scale webinterface.

==== Exploring the Robot API

There are a number of ways to test the connectivity from your PC via 3Scale to 
the robot (there are a couple of hops involved, check back to the 
architecture). You basically need to construct an URL to query the API using 
the 3Scale access token.

While in the 3Scale web UI access the *DOCUMENTATION* link in the menu bar. 
Here you will find the API documentation of all robot operation currently 
exposed in OpenAPI/Swagger format.

You can test the available API calls from here, this will actually go to your 
robot. Just remember to fill in `*<GUID>*` as `USER_KEY` when you test.  

=== Accessing OpenShift

Now that you can access and control your robot through the API let's get 
started with programming the robot by developing applications on our container 
platform. 

Your team user has already been created for you, your user name is `*<GUID>*`. Click on the link below and access the OpenShift web UI:

https://master.berlin-618f.openshiftworkshop.com/console[https://master.berlin-618f.openshiftworkshop.com/console^]

* Login as your team user, `*<GUID>*`, the password will be provided. 
* Look around
* You will see an error: `An error occurred getting metrics.` This is ok, because we don't installed Metrics. Please click on `*Don't Show Me Again*`.

=== Your first application

So we are ready to start some coding. Normally you would now have to setup your 
dev environment... install IDE, language runtimes, build tool, version control 
system/access, checkout code.... etc. And most of this specific to your OS.

Because we work in a cutting edge environment we'll use CodeReady
a browser-based, cloud-native IDE running in the OpenShift environment.

Access CodeReady in your browser:

http://che-lab-infra.apps.berlin-618f.openshiftworkshop.com/[http://che-lab-infra.apps.berlin-618f.openshiftworkshop.com/^]


Login with `*<GUID>*` as username and the provided password.

CodeReady provides development environment for several languages and runtimes. You have the choice between Python, php and Java.

==== Launch your workspace from CodeReady

After login you are in the Workspace management view of CodeReady. Add your 
workspace in CodeReady and choose `Java` or `Python` or `php` as your programming language:

* *NAME*: `<GUID>-robot-app-workspace` 
* *SELECT STACK*: `Java` / `Python` / `php`
* Click `*CREATE*`
* After creation has finished a pop-up appears, click *OPEN*.

Now your CodeReady workspace should open in your browser. 

TIP: Creating a new workspace can take some time.

==== Get Application Quickstart, which one depends on your choice before

===== https://adoc.redhat.partners/lab/build-github.php?guid=<GUID>&file=robot-python-module.adoc&dir=/nexus-Six/openshift-robot-hackathon/master/doc/[Go on with Python^]

===== https://adoc.redhat.partners/lab/build-github.php?guid=<GUID>&file=robot-php-module.adoc&dir=/nexus-Six/openshift-robot-hackathon/master/doc/[Go on with php^]

===== https://adoc.redhat.partners/lab/build-github.php?guid=<GUID>&file=robot-java-module.adoc&dir=/nexus-Six/openshift-robot-hackathon/master/doc/[Go on with Java^]

== Now the Fun Starts! 

Now you should have all the information to start hacking the robot!

=== Challenge

Task: Make your robot drive in a square with approx 20cm edge length

Hints:

* Plan what your robot should do, check the space for the square.
* Look up the API calls you need (remember the API documentation?)
* Change the code in the *run()* method (have a look at the commented out code 
examples)
* Test locally in Che if you want to
* Deploy to OpenShift

WARNING: Solution (Java) Below!

----
 MultiValueMap<String, String> paramMap = new LinkedMultiValueMap<String, 
String>();
        paramMap.add("user_key", "<API Key");
        HttpEntity<MultiValueMap<String, String>> request = new 
HttpEntity<MultiValueMap<String, String>>(paramMap,
                new LinkedMultiValueMap<String, String>());
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
----

=== Missions

* Mission 1 : Have the robot stop exactly at a certain point
* Mission 2 : Use Distance Sensor: Stop in front of the robot barrier
* Mission 3 : Navigate a predefined labyrinth
* Mission 4 : Navigate an unknown labyrinth

== Links

3Scale Web UI: +
https://rh-test.3scale.net/[https://rh-test.3scale.net/^]

OpenShift Web UI: +
https://master.berlin-618f.openshiftworkshop.com/console[https://master.berlin-618f.openshiftworkshop.com/console^]

Che Web UI: +
http://che-lab-infra.apps.berlin-618f.openshiftworkshop.com/[http://che-lab-infra.apps.berlin-618f.openshiftworkshop.com/^]

Gogs Web UI: +
http://gogs-lab-infra.apps.berlin-618f.openshiftworkshop.com[http://gogs-lab-infra.apps.berlin-618f.openshiftworkshop.com^]








