metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ${project.artifactId}
spec:
  replicas: 1
  template:
    spec:      
      containers:
        - env:
            - name: MAP
              valueFrom:
                configMapKeyRef:
                  key: MAP
                  name: robot-mapping-configmap